name: flutter_firebase_analytics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_analytics: ^10.10.7
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  js: ^0.7.1

  # Authentication
  google_sign_in: 6.1.6  # Pin to specific version
  flutter_facebook_auth: ^6.0.4

  # UI and State Management
  provider: ^6.1.5
  get_it: ^7.6.4
  injectable: ^2.1.0
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.1.0
  intl: ^0.17.0
  fl_chart: ^0.66.0
  uuid: ^4.2.1
  faker: ^2.1.0

dependency_overrides:
  google_sign_in_ios: 5.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
